---
- name: Launch an Amazon EC2 instance from localhost
  hosts: localhost
  connection: local
  gather_facts: False

  roles:
    - ec2_instance

- name: Provision the EC2 instance with Docker and nginx
  hosts: nginx-test
  gather_facts: False
  user: ec2-user

  roles:
    - docker
    - nginx

